specify python=3.8 in snakemake env because latest python (3.11) raises an error when starting snakemake: python3.11/site-packages/ratelimiter.py, line 127, in RateLimiter __aexit__ = asyncio.coroutine(__exit__) AttributeError: module 'asyncio' has no attribute 'coroutine'